"""Context construction, preparation, and run-state types."""

from .builder import ContextBuilder
from .compaction_state import (
    ExecutionCompactionState,
    SemanticCompactionState,
    SessionCompactionState,
)
from .compression import build_observation
from .history_compaction import (
    COMPACTED_EXECUTION_HEADING,
    CURRENT_TOOL_FRONTIER_HEADING,
    compact_current_tool_frontier,
    compact_execution_history,
    compact_execution_history_with_details,
)
from .message_groups import (
    bounded_messages,
    find_final_assistant_group,
    find_latest_user_group_index,
    flatten_groups,
    group_messages,
    is_final_assistant_message,
    is_synthetic_assistant_message,
    select_recent_semantic_turns,
    validate_message_protocol,
)
from .policy import CompactionPolicy
from .preparer import (
    ContextPreparer,
    HistoryCompactionPlan,
    PreparedModelRequest,
    PromptBudgetExceeded,
    render_tool_result_message,
)
from .task_projection import (
    CURRENT_TASK_END,
    CURRENT_TASK_HEADING,
    TASK_TOOL_NAMES,
    insert_current_task_record,
    render_current_task_record,
    strip_task_protocol,
)
from .repository_rules import (
    MAX_REPOSITORY_RULE_BYTES,
    RepositoryRuleDocument,
    RepositoryRuleLoader,
    RepositoryRulesSnapshot,
)
from .semantic_compaction import (
    LLMSemanticHistoryCompactor,
    SEMANTIC_COMPACTION_PURPOSE,
    SEMANTIC_HISTORY_HEADING,
    SemanticHistoryCompactionError,
    SemanticHistoryCompactor,
    SemanticHistoryItem,
    SemanticHistorySummary,
    extract_grounding_file_references,
    render_semantic_history,
)
from .run_state import (
    initialize_run_state,
    mark_verification_failed,
    mark_verification_not_run,
    mark_verification_passed,
    mark_verification_rolled_back,
    record_inspected_file,
)
from .system_context import render_repository_structure_card
from .types import (
    BuiltContext,
    ContextCompressionEvent,
    ContextObservation,
    ContextSkill,
    InspectedFile,
    RunState,
    TokenBudget,
    VerificationState,
)

__all__ = [
    "BuiltContext",
    "ContextBuilder",
    "ContextCompressionEvent",
    "ContextObservation",
    "ContextPreparer",
    "CompactionPolicy",
    "ExecutionCompactionState",
    "ContextSkill",
    "HistoryCompactionPlan",
    "InspectedFile",
    "PreparedModelRequest",
    "PromptBudgetExceeded",
    "RepositoryRuleDocument",
    "RepositoryRuleLoader",
    "RepositoryRulesSnapshot",
    "MAX_REPOSITORY_RULE_BYTES",
    "RunState",
    "LLMSemanticHistoryCompactor",
    "SEMANTIC_COMPACTION_PURPOSE",
    "SEMANTIC_HISTORY_HEADING",
    "SemanticHistoryCompactionError",
    "SemanticHistoryCompactor",
    "SemanticHistoryItem",
    "SemanticHistorySummary",
    "SemanticCompactionState",
    "SessionCompactionState",
    "TokenBudget",
    "CURRENT_TASK_END",
    "CURRENT_TASK_HEADING",
    "TASK_TOOL_NAMES",
    "extract_grounding_file_references",
    "VerificationState",
    "bounded_messages",
    "find_final_assistant_group",
    "find_latest_user_group_index",
    "COMPACTED_EXECUTION_HEADING",
    "CURRENT_TOOL_FRONTIER_HEADING",
    "build_observation",
    "compact_current_tool_frontier",
    "compact_execution_history",
    "compact_execution_history_with_details",
    "insert_current_task_record",
    "flatten_groups",
    "group_messages",
    "is_final_assistant_message",
    "is_synthetic_assistant_message",
    "select_recent_semantic_turns",
    "initialize_run_state",
    "mark_verification_failed",
    "mark_verification_not_run",
    "mark_verification_passed",
    "mark_verification_rolled_back",
    "record_inspected_file",
    "render_current_task_record",
    "render_repository_structure_card",
    "render_semantic_history",
    "render_tool_result_message",
    "strip_task_protocol",
    "validate_message_protocol",
]
