"""Central limits used by active context modules."""

MAX_CHECKPOINT_OBSERVATIONS = 5

OBSERVATION_TOKEN_LIMIT = 12_000
OBSERVATION_PREVIEW_CHARS = 2_000
READ_FILE_LINE_LIMIT = 800
SEARCH_MATCH_LIMIT = 50
FILE_SEARCH_RESULT_LIMIT = 50
COMMAND_OUTPUT_CHAR_LIMIT = 20_000
FAILED_COMMAND_OUTPUT_CHAR_LIMIT = 6_000
FAILED_COMMAND_PREVIEW_CHAR_LIMIT = 1_800
RAW_TEXT_SUMMARY_CHARS = 2400
IMPORTANT_FAILURE_LINE_LIMIT = 240

MAX_INSPECTED_FILES = 32
