"""Protocol-safe operations for canonical model messages.

An assistant tool-call message and all immediately following matching tool
results form one indivisible group. Every history trim, compaction, session
persistence, and resume validation must operate on these groups rather than on
raw message indexes.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Iterable


Message = dict[str, Any]
MessageGroup = list[Message]

_SYNTHETIC_ASSISTANT_HEADINGS = (
    "[MiniCode compacted execution]",
    "[MiniCode semantic history]",
    "[MiniCode current tool frontier]",
    "[MiniCode current task]",
    "[MiniCode runtime notification]",
)


def is_synthetic_assistant_message(
    message: Message,
    *,
    extra_headings: Iterable[str] = (),
) -> bool:
    """Return whether one plain Assistant message was generated by the Harness."""

    if message.get("role") != "assistant" or message.get("tool_calls"):
        return False
    content = str(message.get("content") or "").strip()
    if not content:
        return False
    headings = tuple(
        dict.fromkeys((*_SYNTHETIC_ASSISTANT_HEADINGS, *tuple(extra_headings)))
    )
    return bool(headings) and content.startswith(headings)


def is_final_assistant_message(
    message: Message,
    *,
    extra_synthetic_headings: Iterable[str] = (),
) -> bool:
    """Return whether one message is a genuine model final answer."""

    return (
        message.get("role") == "assistant"
        and not message.get("tool_calls")
        and bool(str(message.get("content") or "").strip())
        and not is_synthetic_assistant_message(
            message,
            extra_headings=extra_synthetic_headings,
        )
    )


def find_latest_user_group_index(groups: list[MessageGroup]) -> int | None:
    """Return the newest group containing a user message."""

    for index in range(len(groups) - 1, -1, -1):
        if any(message.get("role") == "user" for message in groups[index]):
            return index
    return None


def find_final_assistant_group(
    groups: list[MessageGroup],
    *,
    user_index: int,
    next_user_index: int,
    compacted_execution_heading: str = "[MiniCode compacted execution]",
) -> int | None:
    """Find the last plain assistant answer belonging to one user Turn."""

    for index in range(next_user_index - 1, user_index, -1):
        group = groups[index]
        if len(group) != 1:
            continue
        message = group[0]
        if is_final_assistant_message(
            message,
            extra_synthetic_headings=(compacted_execution_heading,),
        ):
            return index
    return None


def select_recent_semantic_turns(
    groups: list[MessageGroup],
    *,
    active_user_index: int | None = None,
    max_turns: int = 3,
    compacted_execution_heading: str = "[MiniCode compacted execution]",
) -> list[tuple[int, int]]:
    """Return ``(user, final assistant)`` indexes for recent completed Turns."""

    if max_turns < 1:
        return []
    boundary = (
        active_user_index
        if active_user_index is not None
        else find_latest_user_group_index(groups)
    )
    if boundary is None:
        return []

    user_indexes = [
        index
        for index in range(boundary)
        if any(message.get("role") == "user" for message in groups[index])
    ]
    turns: list[tuple[int, int]] = []
    next_user_index = boundary
    for user_index in reversed(user_indexes):
        assistant_index = find_final_assistant_group(
            groups,
            user_index=user_index,
            next_user_index=next_user_index,
            compacted_execution_heading=compacted_execution_heading,
        )
        if assistant_index is not None:
            turns.append((user_index, assistant_index))
            if len(turns) >= max_turns:
                break
        next_user_index = user_index
    turns.reverse()
    return turns


def group_messages(messages: Iterable[Message]) -> list[MessageGroup]:
    """Return protocol-safe canonical message groups."""

    source = [deepcopy(message) for message in messages]
    groups: list[MessageGroup] = []
    index = 0
    while index < len(source):
        message = source[index]
        if message.get("role") == "assistant" and message.get("tool_calls"):
            group = [message]
            expected_ids = {
                str(call.get("id"))
                for call in message.get("tool_calls") or []
                if call.get("id") is not None
            }
            index += 1
            while index < len(source):
                candidate = source[index]
                if candidate.get("role") != "tool":
                    break
                tool_call_id = str(candidate.get("tool_call_id"))
                if expected_ids and tool_call_id not in expected_ids:
                    break
                group.append(candidate)
                index += 1
            groups.append(group)
            continue
        groups.append([message])
        index += 1
    return groups


def flatten_groups(groups: Iterable[MessageGroup]) -> list[Message]:
    """Flatten isolated groups into a canonical message list."""

    return [deepcopy(message) for group in groups for message in group]


def bounded_messages(messages: Iterable[Message], max_messages: int) -> list[Message]:
    """Keep the newest complete groups within an approximate message budget.

    A single group may exceed ``max_messages``; it is retained intact because a
    syntactically valid provider request is more important than the soft count.
    """

    if max_messages < 1:
        return []
    groups = group_messages(messages)
    kept: list[MessageGroup] = []
    count = 0
    for group in reversed(groups):
        if kept and count + len(group) > max_messages:
            break
        kept.append(group)
        count += len(group)
        if count >= max_messages:
            break
    kept.reverse()
    return flatten_groups(kept)


def validate_message_protocol(messages: Iterable[Message]) -> list[str]:
    """Return human-readable protocol errors without mutating history."""

    errors: list[str] = []
    source = list(messages)
    for index, message in enumerate(source):
        if message.get("role") == "tool":
            if index == 0:
                errors.append(f"tool message at index {index} has no assistant tool call")
                continue
            owner_index = index - 1
            while owner_index >= 0 and source[owner_index].get("role") == "tool":
                owner_index -= 1
            owner = source[owner_index] if owner_index >= 0 else None
            tool_ids = {
                str(call.get("id"))
                for call in (owner or {}).get("tool_calls") or []
                if call.get("id") is not None
            }
            if not owner or owner.get("role") != "assistant" or not tool_ids:
                errors.append(f"tool message at index {index} has no assistant tool-call owner")
            elif str(message.get("tool_call_id")) not in tool_ids:
                errors.append(
                    f"tool message at index {index} references unknown tool_call_id "
                    f"{message.get('tool_call_id')!r}"
                )
    return errors
